/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as PublicRouteImport } from './routes/public'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContentRouteImport } from './routes/content'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagNameRouteImport } from './routes/tags.$tagName'
import { Route as SeriesSeriesIdRouteImport } from './routes/series.$seriesId'
import { Route as PublicProfileRouteImport } from './routes/public.profile'
import { Route as PublicContentIdRouteImport } from './routes/public.$contentId'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagNameRoute = TagsTagNameRouteImport.update({
  id: '/tags/$tagName',
  path: '/tags/$tagName',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSeriesIdRoute = SeriesSeriesIdRouteImport.update({
  id: '/series/$seriesId',
  path: '/series/$seriesId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProfileRoute = PublicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContentIdRoute = PublicContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => PublicRoute,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/profile': typeof ProfileRoute
  '/public': typeof PublicRouteWithChildren
  '/recent': typeof RecentRoute
  '/shared': typeof SharedRoute
  '/starred': typeof StarredRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/public/$contentId': typeof PublicContentIdRoute
  '/public/profile': typeof PublicProfileRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/tags/$tagName': typeof TagsTagNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/profile': typeof ProfileRoute
  '/public': typeof PublicRouteWithChildren
  '/recent': typeof RecentRoute
  '/shared': typeof SharedRoute
  '/starred': typeof StarredRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/public/$contentId': typeof PublicContentIdRoute
  '/public/profile': typeof PublicProfileRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/tags/$tagName': typeof TagsTagNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/profile': typeof ProfileRoute
  '/public': typeof PublicRouteWithChildren
  '/recent': typeof RecentRoute
  '/shared': typeof SharedRoute
  '/starred': typeof StarredRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/public/$contentId': typeof PublicContentIdRoute
  '/public/profile': typeof PublicProfileRoute
  '/series/$seriesId': typeof SeriesSeriesIdRoute
  '/tags/$tagName': typeof TagsTagNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/docs'
    | '/editor'
    | '/profile'
    | '/public'
    | '/recent'
    | '/shared'
    | '/starred'
    | '/folders/$folderId'
    | '/public/$contentId'
    | '/public/profile'
    | '/series/$seriesId'
    | '/tags/$tagName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content'
    | '/docs'
    | '/editor'
    | '/profile'
    | '/public'
    | '/recent'
    | '/shared'
    | '/starred'
    | '/folders/$folderId'
    | '/public/$contentId'
    | '/public/profile'
    | '/series/$seriesId'
    | '/tags/$tagName'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/docs'
    | '/editor'
    | '/profile'
    | '/public'
    | '/recent'
    | '/shared'
    | '/starred'
    | '/folders/$folderId'
    | '/public/$contentId'
    | '/public/profile'
    | '/series/$seriesId'
    | '/tags/$tagName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRoute
  DocsRoute: typeof DocsRoute
  EditorRoute: typeof EditorRoute
  ProfileRoute: typeof ProfileRoute
  PublicRoute: typeof PublicRouteWithChildren
  RecentRoute: typeof RecentRoute
  SharedRoute: typeof SharedRoute
  StarredRoute: typeof StarredRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  SeriesSeriesIdRoute: typeof SeriesSeriesIdRoute
  TagsTagNameRoute: typeof TagsTagNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagName': {
      id: '/tags/$tagName'
      path: '/tags/$tagName'
      fullPath: '/tags/$tagName'
      preLoaderRoute: typeof TagsTagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$seriesId': {
      id: '/series/$seriesId'
      path: '/series/$seriesId'
      fullPath: '/series/$seriesId'
      preLoaderRoute: typeof SeriesSeriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/profile': {
      id: '/public/profile'
      path: '/profile'
      fullPath: '/public/profile'
      preLoaderRoute: typeof PublicProfileRouteImport
      parentRoute: typeof PublicRoute
    }
    '/public/$contentId': {
      id: '/public/$contentId'
      path: '/$contentId'
      fullPath: '/public/$contentId'
      preLoaderRoute: typeof PublicContentIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PublicRouteChildren {
  PublicContentIdRoute: typeof PublicContentIdRoute
  PublicProfileRoute: typeof PublicProfileRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicContentIdRoute: PublicContentIdRoute,
  PublicProfileRoute: PublicProfileRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRoute,
  DocsRoute: DocsRoute,
  EditorRoute: EditorRoute,
  ProfileRoute: ProfileRoute,
  PublicRoute: PublicRouteWithChildren,
  RecentRoute: RecentRoute,
  SharedRoute: SharedRoute,
  StarredRoute: StarredRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  SeriesSeriesIdRoute: SeriesSeriesIdRoute,
  TagsTagNameRoute: TagsTagNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
