/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StarredRouteImport } from './routes/starred'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContentRouteImport } from './routes/content'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TagsTagNameRouteImport } from './routes/tags.$tagName'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'

const StarredRoute = StarredRouteImport.update({
  id: '/starred',
  path: '/starred',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TagsTagNameRoute = TagsTagNameRouteImport.update({
  id: '/tags/$tagName',
  path: '/tags/$tagName',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/recent': typeof RecentRoute
  '/shared': typeof SharedRoute
  '/starred': typeof StarredRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/tags/$tagName': typeof TagsTagNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/recent': typeof RecentRoute
  '/shared': typeof SharedRoute
  '/starred': typeof StarredRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/tags/$tagName': typeof TagsTagNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/recent': typeof RecentRoute
  '/shared': typeof SharedRoute
  '/starred': typeof StarredRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/tags/$tagName': typeof TagsTagNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/docs'
    | '/editor'
    | '/recent'
    | '/shared'
    | '/starred'
    | '/folders/$folderId'
    | '/tags/$tagName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content'
    | '/docs'
    | '/editor'
    | '/recent'
    | '/shared'
    | '/starred'
    | '/folders/$folderId'
    | '/tags/$tagName'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/docs'
    | '/editor'
    | '/recent'
    | '/shared'
    | '/starred'
    | '/folders/$folderId'
    | '/tags/$tagName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRoute
  DocsRoute: typeof DocsRoute
  EditorRoute: typeof EditorRoute
  RecentRoute: typeof RecentRoute
  SharedRoute: typeof SharedRoute
  StarredRoute: typeof StarredRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  TagsTagNameRoute: typeof TagsTagNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/starred': {
      id: '/starred'
      path: '/starred'
      fullPath: '/starred'
      preLoaderRoute: typeof StarredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$tagName': {
      id: '/tags/$tagName'
      path: '/tags/$tagName'
      fullPath: '/tags/$tagName'
      preLoaderRoute: typeof TagsTagNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRoute,
  DocsRoute: DocsRoute,
  EditorRoute: EditorRoute,
  RecentRoute: RecentRoute,
  SharedRoute: SharedRoute,
  StarredRoute: StarredRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  TagsTagNameRoute: TagsTagNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
